### ISSUE TITLE
Release Windows/Mac version

### ISSUE THREAD

**Issue by alissonsleal** [khatibomar/chunky#7]
Hey man, awesome tool. I'm the creator of pogu.live and this is one of the most requested features I get. Thank you for creating this.

I don't code in Go, but I believe you can compile it to run as a .exe, if you compile it and send it to other people can they use it even if they don't have Go installed? If they can, maybe you could compile it and release it in the Github Releases section. That way I could just link them here, or even better, I could deep link it and it auto starts chunky to download a VOD.

ref issue https://github.com/Alissonsleal/TwitchSubVod/issues/112

**Comment by khatibomar** [comment]
Hello yes I will work on that ,
I will setup an Go Releaser.

**Comment by khatibomar** [comment]
I added this it doesnt seem to produce binaries I think need to configure the release more

**Comment by khatibomar** [comment]
Hi I added releases for all platforms.
Also I would like to thank you for making pogulive it really helped me out.
